"""Changed yt id in Film

Revision ID: 17edb992fc92
Revises: a2ecd4381637
Create Date: 2020-05-24 16:13:20.126230

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17edb992fc92'
down_revision = 'a2ecd4381637'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Film', sa.Column('yt_trailer_id', sa.String(length=11), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Film', 'yt_trailer_id')
    # ### end Alembic commands ###
