"""Added descr and yt trailer id to Film

Revision ID: 4f2566438e0e
Revises: 
Create Date: 2020-05-24 16:03:19.662572

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f2566438e0e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Film', sa.Column('description', sa.String(length=500), nullable=True))
    op.add_column('Film', sa.Column('yt_trailer_id', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Film', 'yt_trailer_id')
    op.drop_column('Film', 'description')
    # ### end Alembic commands ###
