"""Changed yt id in Film

Revision ID: a2ecd4381637
Revises: 4f2566438e0e
Create Date: 2020-05-24 16:13:08.436158

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a2ecd4381637'
down_revision = '4f2566438e0e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Film', 'yt_trailer_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Film', sa.Column('yt_trailer_id', mysql.VARCHAR(length=10), nullable=True))
    # ### end Alembic commands ###
